/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useMemo, useState } from "react";
import { getStoredLanguage, setStoredLanguage } from "../utils/language";

const LanguageContext = createContext({
  language: "fr",
  setLanguage: () => {},
  t: {},
});

const moduleNames = {
  fr: {
    read: "Compréhension Écrite",
    listen: "Compréhension Orale",
    write: "Expression Écrite",
    speak: "Expression Orale",
    grammar: "Grammaire",
    vocabulary: "Vocabulaire",
  },
  en: {
    read: "Reading Comprehension",
    listen: "Listening Comprehension",
    write: "Written Expression",
    speak: "Speaking",
    grammar: "Grammar",
    vocabulary: "Vocabulary",
  },
  de: {
    read: "Leseverstehen",
    listen: "Hörverstehen",
    write: "Schriftlicher Ausdruck",
    speak: "Mündlicher Ausdruck",
    grammar: "Grammatik",
    vocabulary: "Wortschatz",
  },
};

const translations = {
  fr: {
    common: {
      home: "Accueil",
      about: "À propos",
      contact: "Contact",
      news: "Actualités",
      training: "Formations",
      pages: "Leçons",
      lessons: "Leçons",
      profile: "Profil",
      progress: "Progrès",
      logout: "Déconnexion",
      loading: "Chargement...",
      back: "Retour",
      dashboard: "Dashboard",
      modules: "Modules",
      save: "Sauvegarder",
      next: "Suivant",
      submit: "Soumettre",
      skip: "Passer",
      flag: "Signaler",
    },
    modules: moduleNames.fr,
    auth: {
      loginTitle: "Bon retour",
      loginCta: "Se connecter",
      registerTitle: "Créer un compte",
      registerCta: "S'inscrire",
      backHome: "Retour à l'accueil",
      loginIntro: "Entrez vos identifiants pour continuer vers la simulation.",
      registerIntro: "Remplissez le formulaire pour commencer votre préparation.",
      noAccount: "Pas encore de compte ?",
      alreadyAccount: "Déjà un compte ?",
      signupHere: "Inscrivez-vous ici",
      loginHere: "Connectez-vous",
      loginBrandTitle: "Préparez-vous à l'examen d'allemand.",
      loginBrandText: "Simulations réalistes, suivi des progrès et accompagnement pour passer l'examen en confiance.",
      registerBrandTitle: "Créez votre compte en quelques minutes.",
      registerBrandText: "Accédez aux simulations, suivez vos lacunes et préparez votre certificat d'allemand.",
      emailLogin: "ou avec votre email",
      email: "Email",
      password: "Mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      username: "Nom d'utilisateur",
      firstName: "Prénom",
      lastName: "Nom",
      phoneOptional: "Téléphone (optionnel)",
      terms: "J'accepte les conditions d'utilisation",
      remember: "Se souvenir de moi",
      forgot: "Mot de passe oublié ?",
    },
      landing: {
      nav: {
        services: "Services",
        pricing: "Nos forfaits",
        contact: "Contact",
        login: "Connexion",
        home: "Accueil",
        currentTopics: "Sujets actuels",
        aboutTests: "À propos TestDaF/DSH",
        pages: "Pages",
        createAccount: "Créer un compte",
      },
      heroTitleA: "Dominez l'examen d'allemand.",
      heroTitleB: "Assurez votre certificat.",
      heroSubtitle:
        "Transformez votre stress en automatisme. Des simulations réalistes et un encadrement continu des lacunes avant de passer l'examen officiel.",
      launch: "Lancer ma simulation",
      servicesTitle: "Nos services",
      pricingTitle: "Nos forfaits",
      testimonials: "Avis de nos candidats",
      leaveComment: "Laissez un commentaire",
      partners: "Nos partenaires",
      fullAccess: "Accès complet",
      subscriptionTitle: "Abonnez-vous et profitez d'un accès complet à tous les tests et séries",
      subscriptionIntro: "Débloquez toutes les séries premium, les modules complets et une correction structurée dans un seul espace de préparation.",
      subscriptionFeatures: [
        "Tests complets en conditions réelles avec correction",
        "Tests d'expression écrite en ligne",
        "Suivi efficace pendant toute la préparation",
        "Entraînement d'expression orale en ligne",
      ],
      viewOffers: "Voir les offres",
      tryFree: "Essayer gratuitement",
      thousandsSatisfied: "Des milliers d'étudiants satisfaits",
      reviewsFollowup: "Rejoignez plus de 1000 candidats qui ont réussi avec nous",
      trustTitle: "Ils nous font confiance",
      trustSubtitle: "Des étudiants du monde entier choisissent Deutsch Learning",
      specialLaunch: "Lancement spécial",
      launchTitle: "Prêt à vous tester et à augmenter votre niveau ?",
      launchText: "Rejoignez des milliers d'étudiants qui ont réussi leurs examens grâce à notre plateforme.",
      contact: "Contactez-nous",
      lastName: "Nom",
      firstName: "Prénom",
      email: "Email",
      phone: "Téléphone",
      question: "Comment pouvons-nous vous aider ?",
      send: "Envoyer",
      sent: "Message envoyé avec succès.",
      commentPrompt: "Laissez votre commentaire :",
      stats: ["Étudiants actifs", "Taux de réussite", "Note moyenne"],
      services: [
        "Simulations d'examens réalistes",
        "Entraînement audio et compréhension orale",
        "Correction d'exercices écrits",
        "Pratique de la prononciation",
      ],
      serviceDescriptions: [
        "Entraînez-vous avec des parcours complets, chronométrés et proches de l'examen.",
        "Gagnez en confiance avec des exercices d'écoute ciblés.",
        "Améliorez vos réponses écrites avec un entraînement orienté correction.",
        "Travaillez une expression orale claire et prête pour l'examen.",
        "Visualisez votre progression par compétence.",
        "Préparez-vous à votre rythme avec des séances flexibles.",
        "Travaillez vers des examens reconnus par les institutions.",
        "Progressez avec une communauté d'étudiants motivés.",
      ],
      extraServiceTitles: ["Suivi des progrès", "Horaire flexible", "Certifié et reconnu", "Communauté active"],
      pricing: {
        bronze: {
          subtitle: "Idéal pour se familiariser avec l'examen",
          features: ["Test de niveau complet", "Accès à 5 simulations d'examen", "Correction automatique", "Support par email"],
        },
        silver: {
          subtitle: "Le choix préféré de nos candidats",
          features: ["Tout le contenu Bronze", "Accès illimité aux simulations", "Corrections par un tuteur", "Session de conversation (1h/mois)", "Support prioritaire"],
        },
        gold: {
          subtitle: "L'accompagnement premium pour réussir",
          features: ["Tout le contenu Silver", "Coaching personnel", "Sessions de conversation illimitées", "Garantie de réussite ou remboursé", "Support 24/7"],
        },
      },
      testimonialsText: [
        "Grâce à cette plateforme, j'ai obtenu mon certificat B2 du premier coup. Les simulations sont extrêmement fidèles à la réalité.",
        "Un accompagnement exceptionnel. Le suivi personnalisé m'a permis de corriger mes erreurs récurrentes à l'écrit.",
      ],
    },
    about: {
      title: "À propos de nous",
      subtitle: "Notre Mission : Votre Réussite",
      mission1:
        "Nous avons créé le Deutsch Prüfung pour rendre les certifications allemandes moins stressantes et plus efficaces.",
      mission2:
        "Notre simulation en conditions réelles, couplée à la correction par IA, vous guide pas à pas vers votre diplôme.",
      pillarsTitle: "Les trois piliers de notre solution",
      pillars: ["SIMULATIONS RÉELLES", "CORRECTION PAR IA", "SUIVI DE PROGRÈS"],
      valuesTitle: "Nos Valeurs",
      values: ["EXCELLENCE ACADÉMIQUE", "ACCESSIBILITÉ", "INNOVATION TECHNOLOGIQUE"],
    },
    contactPage: {
      subtitle: "Parlez-nous directement sur WhatsApp ou envoyez-nous un email.",
      whatsapp: "Ouvrir la conversation",
    },
    newsPage: {
      title: "Actualités",
      subtitle: "Retrouvez ici les dernières nouvelles, ressources et mises à jour de préparation à l'examen.",
      items: [
        {
          title: "Nouveaux sujets B2 ajoutés",
          date: "Mai 2026",
          text: "10 nouvelles simulations orientées grammaire et compréhension orale sont disponibles.",
        },
        {
          title: "Atelier live : réussir l'expression écrite",
          date: "Avril 2026",
          text: "Webinaire hebdomadaire avec correction de copies et méthodologie d'examen.",
        },
        {
          title: "Mise à jour des recommandations IA",
          date: "Mars 2026",
          text: "Les feedbacks sont désormais plus détaillés avec priorisation des lacunes.",
        },
      ],
    },
    progressPage: {
      title: "Mon progrès",
      subtitle: "Suivez votre évolution par compétence.",
    },
    profilePage: {
      fullName: "Nom",
      birthDate: "Date de naissance",
      createdAt: "Compte créé",
      username: "Nom d'utilisateur",
      firstName: "Prénom",
      lastName: "Nom",
      saved: "Profil mis à jour.",
      saveChanges: "Enregistrer les modifications",
      saving: "Sauvegarde...",
    },
    dashboard: {
      welcome: "Bienvenue",
      certificationProgress: "Mon progrès de Certification",
      currentLevel: "Niveau actuel au",
      target: "Objectif à atteindre",
      recommendations: "Recommandations de Révision",
      skillsBalance: "Mon Équilibre de compétences",
      recent: "Mes simulations récentes",
      none: "Aucune simulation disponible.",
      details: "Détails",
      newSimulation: "COMMENCER UNE NOUVELLE SIMULATION",
    },
    simulations: {
      title: "Vous êtes sur le point de commencer votre immersion",
      subtitle: "Choisissez une discipline pour débuter votre simulation.",
      minutes: "Minutes",
      questions: "Questions",
    },
    lessons: {
      title: "Leçons",
      subtitle: "Choisissez un manuel et lisez les notes directement dans la plateforme.",
      choose: "Choisir un manuel",
      readingTime: "Lecture",
      level: "Niveau",
      topics: "Sujets",
      open: "Lire ce manuel",
      notes: "Notes de leçon",
      books: [
        {
          id: "grammar",
          title: "Grammaire essentielle A1-B1",
          topic: "Articles, verbes et ordre des mots",
          level: "A1-B1",
          minutes: "18 min",
          summary: "Un manuel court pour revoir les bases qui reviennent dans les examens.",
          notes: [
            "En allemand, le verbe conjugué occupe souvent la deuxième position dans une phrase principale.",
            "Les articles der, die et das doivent être appris avec le nom, car ils influencent les déclinaisons.",
            "Après weil, dass ou wenn, le verbe conjugué va généralement à la fin de la proposition.",
          ],
        },
        {
          id: "reading",
          title: "Méthode de compréhension écrite",
          topic: "Repérage, inférence et gestion du temps",
          level: "B1-C1",
          minutes: "22 min",
          summary: "Des stratégies pour lire vite sans perdre les détails importants.",
          notes: [
            "Lisez d'abord les questions pour savoir quelles informations chercher.",
            "Soulignez les dates, nombres, connecteurs et négations : ils changent souvent le sens.",
            "Pour les questions d'inférence, cherchez l'intention du texte plutôt qu'un mot identique.",
          ],
        },
        {
          id: "writing",
          title: "Expression écrite structurée",
          topic: "Emails, essais et argumentation",
          level: "A2-C1",
          minutes: "25 min",
          summary: "Un guide pour organiser vos réponses et respecter le registre demandé.",
          notes: [
            "Commencez par identifier le destinataire : ami, administration, professeur ou entreprise.",
            "Utilisez des connecteurs comme außerdem, jedoch, deshalb et zum Schluss.",
            "Gardez cinq minutes pour relire la place du verbe, les majuscules des noms et les accords.",
          ],
        },
        {
          id: "speaking",
          title: "Expression orale en examen",
          topic: "Préparation, fluidité et relance",
          level: "A1-C2",
          minutes: "20 min",
          summary: "Des techniques pour parler plus clairement sous pression.",
          notes: [
            "Préparez une structure simple : idée principale, exemple, conclusion courte.",
            "Si un mot manque, reformulez avec une phrase plus simple au lieu de vous arrêter.",
            "Enregistrez-vous régulièrement pour contrôler la durée, le rythme et la prononciation.",
          ],
        },
      ],
    },
    modulePage: {
      freeTraining: "Entraînement libre",
      startSimulation: "Start Simulation",
      locked: "Navigation verrouillée",
      questions: "questions",
      answersSaved: "réponses enregistrées",
      navigation: "Navigation",
      navigationFree: "Revenez librement sur une tâche.",
      navigationLocked: "Avancez dans l'ordre de l'examen.",
      answered: "Répondu",
      skipped: "Passé",
      flagged: "Signalé",
      progression: "Progression",
      passText: "Après 70% ou plus, le parcours augmente la difficulté.",
      saveProgress: "Save Progress",
      flagQuestion: "Flag question",
      removeFlag: "Retirer le signalement",
      result: "Résultat final",
      chooseModule: "Choisir un module",
    },
  },
  en: {
    common: {
      home: "Home",
      about: "About",
      contact: "Contact",
      news: "News",
      training: "Training",
      pages: "Lessons",
      lessons: "Lessons",
      profile: "Profile",
      progress: "Progress",
      logout: "Logout",
      loading: "Loading...",
      back: "Back",
      dashboard: "Dashboard",
      modules: "Modules",
      save: "Save",
      next: "Next",
      submit: "Submit",
      skip: "Skip",
      flag: "Flag",
    },
    modules: moduleNames.en,
    auth: {
      loginTitle: "Welcome back",
      loginCta: "Log in",
      registerTitle: "Create an account",
      registerCta: "Sign up",
      backHome: "Back to home",
      loginIntro: "Enter your credentials to continue to the simulation.",
      registerIntro: "Fill out the form to start your preparation.",
      noAccount: "No account yet?",
      alreadyAccount: "Already have an account?",
      signupHere: "Sign up here",
      loginHere: "Log in",
      loginBrandTitle: "Prepare for your German exam.",
      loginBrandText: "Realistic simulations, progress tracking and guidance to take the exam with confidence.",
      registerBrandTitle: "Create your account in a few minutes.",
      registerBrandText: "Access simulations, track your weak points and prepare your German certificate.",
      emailLogin: "or with your email",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm password",
      username: "Username",
      firstName: "First name",
      lastName: "Last name",
      phoneOptional: "Phone (optional)",
      terms: "I accept the terms of use",
      remember: "Remember me",
      forgot: "Forgot password?",
    },
      landing: {
      nav: {
        services: "Services",
        pricing: "Plans",
        contact: "Contact",
        login: "Login",
        home: "Home",
        currentTopics: "Current topics",
        aboutTests: "About TestDaF/DSH",
        pages: "Pages",
        createAccount: "Create an account",
      },
      heroTitleA: "Master your German exam.",
      heroTitleB: "Secure your certificate.",
      heroSubtitle:
        "Turn exam stress into confidence with realistic simulations and continuous guidance before your official exam.",
      launch: "Start my simulation",
      servicesTitle: "Our services",
      pricingTitle: "Our plans",
      testimonials: "Student reviews",
      leaveComment: "Leave a comment",
      partners: "Our partners",
      fullAccess: "Full access",
      subscriptionTitle: "Subscribe and Enjoy Full Access to All Tests and Series",
      subscriptionIntro: "Unlock every premium series, complete exam modules, and structured correction in one clear preparation space.",
      subscriptionFeatures: [
        "Full tests in real conditions with correction",
        "Online written expression tests",
        "Effective tracking throughout preparation",
        "Online oral expression practice",
      ],
      viewOffers: "View offers",
      tryFree: "Try for free",
      thousandsSatisfied: "Thousands of students satisfied",
      reviewsFollowup: "Join over 1000 successful candidates who succeeded with us",
      trustTitle: "They Trust Us",
      trustSubtitle: "Students from all over the world choose Deutsch Learning",
      specialLaunch: "Special launch",
      launchTitle: "Ready to test and increase your level?",
      launchText: "Join thousands of students who have passed their exams thanks to our platform.",
      contact: "Contact us",
      lastName: "Last name",
      firstName: "First name",
      email: "Email",
      phone: "Phone",
      question: "How can we help you?",
      send: "Send",
      sent: "Message sent successfully.",
      commentPrompt: "Leave your comment:",
      stats: ["Active students", "Success rate", "Average rating"],
      services: ["Realistic exam simulations", "Audio and listening practice", "Written exercise correction", "Pronunciation practice"],
      serviceDescriptions: [
        "Practice complete exam flows with realistic timing and structure.",
        "Build confidence with focused listening exercises and replay practice.",
        "Improve written answers with correction-oriented training.",
        "Train clear pronunciation and exam-ready speaking responses.",
        "See your growth by skill and know what to revise next.",
        "Prepare at your own pace with sessions that fit your week.",
        "Work toward exams trusted by universities and institutions.",
        "Learn beside other motivated students preparing for success.",
      ],
      extraServiceTitles: ["Progress Tracking", "Flexible Schedule", "Certified and Recognized", "Active Community"],
      pricing: {
        bronze: {
          subtitle: "Ideal for getting familiar with the exam",
          features: ["Complete placement test", "Access to 5 exam simulations", "Automatic correction", "Email support"],
        },
        silver: {
          subtitle: "Our candidates' favorite choice",
          features: ["Everything in Bronze", "Unlimited simulation access", "Tutor corrections", "Conversation session (1h/month)", "Priority support"],
        },
        gold: {
          subtitle: "Premium support for success",
          features: ["Everything in Silver", "Personal coaching", "Unlimited conversation sessions", "Success guarantee or refund", "24/7 support"],
        },
      },
      testimonialsText: [
        "Thanks to this platform, I passed my B2 certificate on the first try. The simulations are extremely realistic.",
        "Outstanding support. The personalized tracking helped me correct recurring writing mistakes.",
      ],
    },
    about: {
      title: "About us",
      subtitle: "Our Mission: Your Success",
      mission1: "We created Deutsch Prüfung to make German certifications less stressful and more effective.",
      mission2: "Our real-exam simulations, combined with AI correction, guide you step by step toward your certificate.",
      pillarsTitle: "The three pillars of our solution",
      pillars: ["REAL SIMULATIONS", "AI CORRECTION", "PROGRESS TRACKING"],
      valuesTitle: "Our Values",
      values: ["ACADEMIC EXCELLENCE", "ACCESSIBILITY", "TECHNOLOGICAL INNOVATION"],
    },
    contactPage: {
      subtitle: "Reach us directly on WhatsApp or by email.",
      whatsapp: "Open the conversation",
    },
    newsPage: {
      title: "News",
      subtitle: "Find the latest updates, resources, and exam preparation announcements.",
      items: [
        {
          title: "New B2 topics added",
          date: "May 2026",
          text: "10 new simulations focused on grammar and listening comprehension are available.",
        },
        {
          title: "Live workshop: succeed in writing",
          date: "April 2026",
          text: "Weekly webinar with essay correction and exam methodology.",
        },
        {
          title: "AI recommendation update",
          date: "March 2026",
          text: "Feedback is now more detailed with prioritized weaknesses.",
        },
      ],
    },
    progressPage: {
      title: "My progress",
      subtitle: "Track your evolution by skill.",
    },
    profilePage: {
      fullName: "Name",
      birthDate: "Date of birth",
      createdAt: "Account created",
      username: "Username",
      firstName: "First name",
      lastName: "Last name",
      saved: "Profile updated.",
      saveChanges: "Save changes",
      saving: "Saving...",
    },
    dashboard: {
      welcome: "Welcome",
      certificationProgress: "My certification progress",
      currentLevel: "Current level at",
      target: "Target to reach",
      recommendations: "Revision recommendations",
      skillsBalance: "My skill balance",
      recent: "My recent simulations",
      none: "No simulation available.",
      details: "Details",
      newSimulation: "START A NEW SIMULATION",
    },
    simulations: {
      title: "You are about to begin your immersion",
      subtitle: "Choose a discipline to start your simulation.",
      minutes: "Minutes",
      questions: "Questions",
    },
    lessons: {
      title: "Lessons",
      subtitle: "Choose a textbook and read the notes directly inside the platform.",
      choose: "Choose a textbook",
      readingTime: "Reading",
      level: "Level",
      topics: "Topics",
      open: "Read this textbook",
      notes: "Lesson notes",
      books: [
        {
          id: "grammar",
          title: "Essential Grammar A1-B1",
          topic: "Articles, verbs and word order",
          level: "A1-B1",
          minutes: "18 min",
          summary: "A short textbook to review the foundations that often appear in exams.",
          notes: [
            "In German, the conjugated verb often takes the second position in a main clause.",
            "Articles der, die and das should be learned with the noun because they affect declension.",
            "After weil, dass or wenn, the conjugated verb usually goes to the end of the clause.",
          ],
        },
        {
          id: "reading",
          title: "Reading comprehension method",
          topic: "Scanning, inference and time management",
          level: "B1-C1",
          minutes: "22 min",
          summary: "Strategies for reading quickly without missing important details.",
          notes: [
            "Read the questions first so you know which information to look for.",
            "Underline dates, numbers, connectors and negations: they often change the meaning.",
            "For inference questions, look for the text's intention rather than an identical word.",
          ],
        },
        {
          id: "writing",
          title: "Structured written expression",
          topic: "Emails, essays and argumentation",
          level: "A2-C1",
          minutes: "25 min",
          summary: "A guide for organizing answers and respecting the required register.",
          notes: [
            "Start by identifying the recipient: friend, administration, teacher or company.",
            "Use connectors such as außerdem, jedoch, deshalb and zum Schluss.",
            "Keep five minutes to review verb position, noun capitalization and agreements.",
          ],
        },
        {
          id: "speaking",
          title: "Speaking in the exam",
          topic: "Preparation, fluency and follow-up questions",
          level: "A1-C2",
          minutes: "20 min",
          summary: "Techniques to speak more clearly under pressure.",
          notes: [
            "Prepare a simple structure: main idea, example, short conclusion.",
            "If a word is missing, rephrase with a simpler sentence instead of stopping.",
            "Record yourself regularly to control duration, rhythm and pronunciation.",
          ],
        },
      ],
    },
    modulePage: {
      freeTraining: "Free training",
      startSimulation: "Start Simulation",
      locked: "Navigation locked",
      questions: "questions",
      answersSaved: "answers saved",
      navigation: "Navigation",
      navigationFree: "Move freely between tasks.",
      navigationLocked: "Move forward in exam order.",
      answered: "Answered",
      skipped: "Skipped",
      flagged: "Flagged",
      progression: "Progression",
      passText: "After 70% or more, the path increases difficulty.",
      saveProgress: "Save Progress",
      flagQuestion: "Flag question",
      removeFlag: "Remove flag",
      result: "Final result",
      chooseModule: "Choose a module",
    },
  },
  de: {
    common: {
      home: "Start",
      about: "Über uns",
      contact: "Kontakt",
      news: "Nachrichten",
      training: "Kurse",
      pages: "Lektionen",
      lessons: "Lektionen",
      profile: "Profil",
      progress: "Fortschritt",
      logout: "Abmelden",
      loading: "Lädt...",
      back: "Zurück",
      dashboard: "Dashboard",
      modules: "Module",
      save: "Speichern",
      next: "Weiter",
      submit: "Abgeben",
      skip: "Überspringen",
      flag: "Markieren",
    },
    modules: moduleNames.de,
    auth: {
      loginTitle: "Willkommen zurück",
      loginCta: "Anmelden",
      registerTitle: "Konto erstellen",
      registerCta: "Registrieren",
      backHome: "Zurück zur Startseite",
      loginIntro: "Geben Sie Ihre Zugangsdaten ein, um zur Simulation fortzufahren.",
      registerIntro: "Füllen Sie das Formular aus, um mit der Vorbereitung zu beginnen.",
      noAccount: "Noch kein Konto?",
      alreadyAccount: "Schon ein Konto?",
      signupHere: "Hier registrieren",
      loginHere: "Anmelden",
      loginBrandTitle: "Bereiten Sie sich auf die Deutschprüfung vor.",
      loginBrandText: "Realistische Simulationen, Fortschrittsverfolgung und Begleitung für eine sichere Prüfung.",
      registerBrandTitle: "Erstellen Sie Ihr Konto in wenigen Minuten.",
      registerBrandText: "Nutzen Sie Simulationen, verfolgen Sie Ihre Lücken und bereiten Sie Ihr Deutschzertifikat vor.",
      emailLogin: "oder mit Ihrer E-Mail",
      email: "E-Mail",
      password: "Passwort",
      confirmPassword: "Passwort bestätigen",
      username: "Benutzername",
      firstName: "Vorname",
      lastName: "Nachname",
      phoneOptional: "Telefon (optional)",
      terms: "Ich akzeptiere die Nutzungsbedingungen",
      remember: "Angemeldet bleiben",
      forgot: "Passwort vergessen?",
    },
      landing: {
      nav: {
        services: "Leistungen",
        pricing: "Pakete",
        contact: "Kontakt",
        login: "Anmelden",
        home: "Start",
        currentTopics: "Aktuelle Themen",
        aboutTests: "Über TestDaF/DSH",
        pages: "Seiten",
        createAccount: "Konto erstellen",
      },
      heroTitleA: "Meistern Sie die Deutschprüfung.",
      heroTitleB: "Sichern Sie Ihr Zertifikat.",
      heroSubtitle:
        "Verwandeln Sie Prüfungsstress in Sicherheit mit realistischen Simulationen und kontinuierlicher Betreuung vor der offiziellen Prüfung.",
      launch: "Simulation starten",
      servicesTitle: "Unsere Leistungen",
      pricingTitle: "Unsere Pakete",
      testimonials: "Erfahrungen unserer Kandidaten",
      leaveComment: "Kommentar hinterlassen",
      partners: "Unsere Partner",
      fullAccess: "Voller Zugriff",
      subscriptionTitle: "Abonnieren Sie und erhalten Sie vollen Zugriff auf alle Tests und Serien",
      subscriptionIntro: "Schalten Sie alle Premium-Serien, vollständige Prüfungsmodule und strukturierte Korrekturen in einem klaren Vorbereitungsbereich frei.",
      subscriptionFeatures: [
        "Vollständige Tests unter realen Bedingungen mit Korrektur",
        "Online-Tests für schriftlichen Ausdruck",
        "Effektive Begleitung während der Vorbereitung",
        "Online-Training für mündlichen Ausdruck",
      ],
      viewOffers: "Angebote ansehen",
      tryFree: "Kostenlos testen",
      thousandsSatisfied: "Tausende zufriedene Lernende",
      reviewsFollowup: "Schließen Sie sich über 1000 erfolgreichen Kandidaten an",
      trustTitle: "Sie vertrauen uns",
      trustSubtitle: "Lernende aus der ganzen Welt wählen Deutsch Learning",
      specialLaunch: "Sonderstart",
      launchTitle: "Bereit, sich zu testen und Ihr Niveau zu steigern?",
      launchText: "Schließen Sie sich Tausenden von Lernenden an, die ihre Prüfungen dank unserer Plattform bestanden haben.",
      contact: "Kontaktieren Sie uns",
      lastName: "Nachname",
      firstName: "Vorname",
      email: "E-Mail",
      phone: "Telefon",
      question: "Wie können wir Ihnen helfen?",
      send: "Senden",
      sent: "Nachricht erfolgreich gesendet.",
      commentPrompt: "Hinterlassen Sie Ihren Kommentar:",
      stats: ["Aktive Lernende", "Erfolgsquote", "Durchschnittsbewertung"],
      services: ["Realistische Prüfungssimulationen", "Audio- und Hörtraining", "Korrektur schriftlicher Übungen", "Aussprachetraining"],
      serviceDescriptions: [
        "Üben Sie vollständige Prüfungsabläufe mit realistischer Zeitstruktur.",
        "Bauen Sie Sicherheit mit gezieltem Hörtraining auf.",
        "Verbessern Sie schriftliche Antworten mit korrekturorientiertem Training.",
        "Trainieren Sie klare Aussprache und prüfungsreife Antworten.",
        "Sehen Sie Ihren Fortschritt nach Kompetenz und wissen Sie, was Sie wiederholen müssen.",
        "Bereiten Sie sich flexibel in Ihrem eigenen Tempo vor.",
        "Arbeiten Sie auf Prüfungen hin, die von Institutionen anerkannt werden.",
        "Lernen Sie mit anderen motivierten Kandidaten.",
      ],
      extraServiceTitles: ["Fortschrittsverfolgung", "Flexibler Zeitplan", "Zertifiziert und anerkannt", "Aktive Gemeinschaft"],
      pricing: {
        bronze: {
          subtitle: "Ideal, um die Prüfung kennenzulernen",
          features: ["Vollständiger Einstufungstest", "Zugang zu 5 Prüfungssimulationen", "Automatische Korrektur", "Support per E-Mail"],
        },
        silver: {
          subtitle: "Die bevorzugte Wahl unserer Kandidaten",
          features: ["Alles aus Bronze", "Unbegrenzter Zugang zu Simulationen", "Korrekturen durch einen Tutor", "Konversationssitzung (1h/Monat)", "Priorisierter Support"],
        },
        gold: {
          subtitle: "Premium-Begleitung für Ihren Erfolg",
          features: ["Alles aus Silver", "Persönliches Coaching", "Unbegrenzte Konversationssitzungen", "Erfolgsgarantie oder Rückerstattung", "Support 24/7"],
        },
      },
      testimonialsText: [
        "Dank dieser Plattform habe ich mein B2-Zertifikat beim ersten Versuch bestanden. Die Simulationen sind sehr realistisch.",
        "Außergewöhnliche Begleitung. Die persönliche Auswertung half mir, wiederkehrende Schreibfehler zu korrigieren.",
      ],
    },
    about: {
      title: "Über uns",
      subtitle: "Unsere Mission: Ihr Erfolg",
      mission1: "Wir haben Deutsch Prüfung entwickelt, um deutsche Zertifizierungen weniger stressig und wirksamer zu machen.",
      mission2: "Unsere realistischen Simulationen mit KI-Korrektur begleiten Sie Schritt für Schritt zum Zertifikat.",
      pillarsTitle: "Die drei Säulen unserer Lösung",
      pillars: ["ECHTE SIMULATIONEN", "KI-KORREKTUR", "FORTSCHRITTSVERFOLGUNG"],
      valuesTitle: "Unsere Werte",
      values: ["AKADEMISCHE EXZELLENZ", "ZUGÄNGLICHKEIT", "TECHNOLOGISCHE INNOVATION"],
    },
    contactPage: {
      subtitle: "Kontaktieren Sie uns direkt über WhatsApp oder per E-Mail.",
      whatsapp: "Gespräch öffnen",
    },
    newsPage: {
      title: "Nachrichten",
      subtitle: "Hier finden Sie aktuelle Neuigkeiten, Lernressourcen und Plattform-Updates.",
      items: [
        {
          title: "Neue B2-Themen hinzugefügt",
          date: "Mai 2026",
          text: "10 neue Simulationen zu Grammatik und Hörverstehen sind verfügbar.",
        },
        {
          title: "Live-Workshop: schriftlicher Ausdruck",
          date: "April 2026",
          text: "Wöchentliches Webinar mit Textkorrektur und Prüfungsmethodik.",
        },
        {
          title: "Update der KI-Empfehlungen",
          date: "März 2026",
          text: "Feedbacks sind jetzt detaillierter und priorisieren die wichtigsten Lücken.",
        },
      ],
    },
    progressPage: {
      title: "Mein Fortschritt",
      subtitle: "Verfolgen Sie Ihre Entwicklung nach Kompetenz.",
    },
    profilePage: {
      fullName: "Name",
      birthDate: "Geburtsdatum",
      createdAt: "Konto erstellt",
      username: "Benutzername",
      firstName: "Vorname",
      lastName: "Nachname",
      saved: "Profil aktualisiert.",
      saveChanges: "Änderungen speichern",
      saving: "Speichert...",
    },
    dashboard: {
      welcome: "Willkommen",
      certificationProgress: "Mein Zertifikatsfortschritt",
      currentLevel: "Aktuelles Niveau",
      target: "Zielniveau",
      recommendations: "Wiederholungsempfehlungen",
      skillsBalance: "Mein Kompetenzgleichgewicht",
      recent: "Meine letzten Simulationen",
      none: "Keine Simulation verfügbar.",
      details: "Details",
      newSimulation: "NEUE SIMULATION STARTEN",
    },
    simulations: {
      title: "Sie beginnen gleich Ihre Immersion",
      subtitle: "Wählen Sie einen Bereich, um die Simulation zu starten.",
      minutes: "Minuten",
      questions: "Fragen",
    },
    lessons: {
      title: "Lektionen",
      subtitle: "Wählen Sie ein Lehrbuch und lesen Sie die Notizen direkt in der Plattform.",
      choose: "Lehrbuch auswählen",
      readingTime: "Lesezeit",
      level: "Niveau",
      topics: "Themen",
      open: "Dieses Lehrbuch lesen",
      notes: "Lektionsnotizen",
      books: [
        {
          id: "grammar",
          title: "Wichtige Grammatik A1-B1",
          topic: "Artikel, Verben und Wortstellung",
          level: "A1-B1",
          minutes: "18 min",
          summary: "Ein kurzes Lehrbuch zu den Grundlagen, die oft in Prüfungen vorkommen.",
          notes: [
            "Im Deutschen steht das konjugierte Verb im Hauptsatz oft an zweiter Position.",
            "Die Artikel der, die und das sollten mit dem Nomen gelernt werden, weil sie die Deklination beeinflussen.",
            "Nach weil, dass oder wenn steht das konjugierte Verb meistens am Ende des Nebensatzes.",
          ],
        },
        {
          id: "reading",
          title: "Methode für das Leseverstehen",
          topic: "Suchen, Schlussfolgern und Zeitmanagement",
          level: "B1-C1",
          minutes: "22 min",
          summary: "Strategien, um schnell zu lesen, ohne wichtige Details zu verlieren.",
          notes: [
            "Lesen Sie zuerst die Fragen, damit Sie wissen, welche Informationen wichtig sind.",
            "Markieren Sie Daten, Zahlen, Konnektoren und Verneinungen: Sie verändern oft die Bedeutung.",
            "Bei Inferenzfragen suchen Sie die Absicht des Textes, nicht nur ein identisches Wort.",
          ],
        },
        {
          id: "writing",
          title: "Strukturierter schriftlicher Ausdruck",
          topic: "E-Mails, Aufsätze und Argumentation",
          level: "A2-C1",
          minutes: "25 min",
          summary: "Ein Leitfaden, um Antworten zu ordnen und das geforderte Register einzuhalten.",
          notes: [
            "Bestimmen Sie zuerst den Empfänger: Freund, Verwaltung, Lehrkraft oder Unternehmen.",
            "Nutzen Sie Konnektoren wie außerdem, jedoch, deshalb und zum Schluss.",
            "Planen Sie fünf Minuten für die Kontrolle von Verbposition, Großschreibung der Nomen und Endungen ein.",
          ],
        },
        {
          id: "speaking",
          title: "Mündlicher Ausdruck in der Prüfung",
          topic: "Vorbereitung, Flüssigkeit und Rückfragen",
          level: "A1-C2",
          minutes: "20 min",
          summary: "Techniken, um unter Druck klarer zu sprechen.",
          notes: [
            "Bereiten Sie eine einfache Struktur vor: Hauptidee, Beispiel, kurze Schlussfolgerung.",
            "Wenn ein Wort fehlt, formulieren Sie einfacher, statt stehen zu bleiben.",
            "Nehmen Sie sich regelmäßig auf, um Dauer, Rhythmus und Aussprache zu kontrollieren.",
          ],
        },
      ],
    },
    modulePage: {
      freeTraining: "Freies Training",
      startSimulation: "Simulation starten",
      locked: "Navigation gesperrt",
      questions: "Fragen",
      answersSaved: "Antworten gespeichert",
      navigation: "Navigation",
      navigationFree: "Sie können frei zwischen Aufgaben wechseln.",
      navigationLocked: "Gehen Sie in Prüfungsreihenfolge vor.",
      answered: "Beantwortet",
      skipped: "Übersprungen",
      flagged: "Markiert",
      progression: "Fortschritt",
      passText: "Ab 70% wird der Schwierigkeitsgrad erhöht.",
      saveProgress: "Fortschritt speichern",
      flagQuestion: "Aufgabe markieren",
      removeFlag: "Markierung entfernen",
      result: "Endergebnis",
      chooseModule: "Modul wählen",
    },
  },
};

export const getTranslations = (language = "fr") => translations[language] ?? translations.fr;

export function LanguageProvider({ children }) {
  const [language, setLangState] = useState(getStoredLanguage);
  const setLanguage = (next) => setLangState(setStoredLanguage(next));

  const value = useMemo(
    () => ({ language, setLanguage, t: getTranslations(language) }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
